### PR TITLE
skip cuda mem_get_info if cuda is not available

### PR DESCRIPTION
**Pull request by WojtekKowaluk**
Running on MacBook with https://github.com/ai-forever/Kandinsky-2/pull/36
and command line:
`python src/kubin.py --device mps`
However small fix is also required in kubin.

### CODE REVIEW

**Comment by seruva19** [comment]
Thank you!

**Comment by adrianpuiu** [comment]
can't launch with [ --device mps ]. im getting : 
`    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
`

**Comment by seruva19** [comment]
When exactly is this error raised, do you have stacktrace?
Also, @WojtekKowaluk, are you getting the same error?

**Comment by adrianpuiu** [comment]
> When exactly is this error raised, do you have stacktrace? Also, @WojtekKowaluk, are you getting the same error?

right after hitting on generate . i mean im launching with device mps . all good, it loads , and when i hit generate i get [this](https://drive.google.com/file/d/1J_4kiNlRlrYkYuxnRA57L1fWv37UWiq9/view?usp=sharing)

**Comment by WojtekKowaluk** [comment]
@adrianpuiu: seems you are not using my kandinski branch, it is not merged to master:
```
source venv/bin/activate
pip uninstall kandinsky2
pip install -U git+https://github.com/WojtekKowaluk/Kandinsky-2@cpu-mps-fix
```
Let me know if that works

**Comment by adrianpuiu** [comment]
aaaaahhh , makes sense  man :))) , let me give it a shot ..  i let you know in couple of mintues

**Comment by adrianpuiu** [comment]
> ```
> pip install git+https://github.com/WojtekKowaluk/Kandinsky-2@cpu-mps-fix
> ```

[heres](https://drive.google.com/file/d/1uA2CHjM56iB4yW_7N7VSYzBIuo80HcEF/view?usp=sharing) the stack trace. still dosent want , now its throwing  out ssl cert errors :     File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

**Comment by seruva19** [comment]
Try `pip install certifi`

**Comment by adrianpuiu** [comment]
installing certificates from the **/Applications/Python3.10/install.certificates.command**  ..
 now its loading the models into ram .. so it passed. It's all good .

**Comment by adrianpuiu** [comment]
> Try `pip install certifi`

that was it .  pip install --upgrade certifi

**Comment by WojtekKowaluk** [comment]
I rebased mac specific fixes for latest kandinsky repo which kubin is now using and put that into new branch. you can install this new branch inside your kubin virtualevn like this:
```
source venv/bin/activate
pip uninstall kandinsky2
pip install git+https://github.com/WojtekKowaluk/Kandinsky-2@cpu-mps-fix
```
I did not look yet into what we need to get 2.2 and diffusers pipeline working, this is just to keep 2.1 working on latest kubin on mac.

**Comment by seruva19** [comment]
OK, thank you.
There is a link to this thread in wiki so mac users could find and follow your instructions.
I have no way to test it on mac anyway, so that's all I can do for now.

**Comment by orcinus** [comment]
Followed the outlined steps, got everything seemingly working, however, all images produced are either all black pixels, or magenta mess. No errors or anything obviously wrong in the output or logs. No idea what's wrong...

**Comment by seruva19** [comment]
I am afraid I cannot really help you here, as I don't have access to Apple machines and unable to test how Kandinsky works there. Are other PyTorch-powered applications (Automatic1111, etc.) working as expected? And did you try to run Kandinsky using other applications like SD.Next?

**Comment by orcinus** [comment]
Yes, and yes. That's why i'm finding this so puzzling.
I'd get it if it didn't work at all or threw an exception, but everything *seems* fine.

Kandinsky worked in SD.Next as expected, until the yesterday's dev->master merge (but it's failing there now in a different way - namely, unable to load the model).

**Comment by seruva19** [comment]
There were some significant changes in commit c84c0ac, try checkout to any earlier version, for instance 928fb6b (`git checkout 928fb6b`) and see if it still fails to run.

**Comment by orcinus** [comment]
Thanks! Will give it a shot over the weekend!

**Comment by orcinus** [comment]
No luck, unfortunately.
Oh well, i'll be back on my intel machine soon anyway.

**Pull request merged**
