### PR TITLE
add scripts and UI for fine-tuning

### PR DESCRIPTION
**Pull request by seruva19**

### CODE REVIEW

**Comment by adrianpuiu** [comment]
i can't fetch from training to test, is git havin network issues ?

**Comment by seruva19** [comment]
Hmm, it's fine for me.
But training brach is now fully merged into dev, so you can use dev for testing.
And I will remove training branch shortly anyway.

I was just writing about training UI [here](https://github.com/seruva19/kubin/discussions/10), but you beat me to it :)

**Comment by adrianpuiu** [comment]
Apparently the peering is down on my ISP .  Got the dev branch in the end
but it took way too long

**Comment by adrianpuiu** [comment]
*train/dataset.csv does not exist  *
Traceback (most recent call last):
  File
"/home/agp/kubin/venv/lib/python3.10/site-packages/gradio/routes.py", line
412, in run_predict
    output = await app.get_blocks().process_api(
  File
"/home/agp/kubin/venv/lib/python3.10/site-packages/gradio/blocks.py", line
1299, in process_api
    result = await self.call_function(
  File
"/home/agp/kubin/venv/lib/python3.10/site-packages/gradio/blocks.py", line
1021, in call_function
    prediction = await anyio.to_thread.run_sync(
  File
"/home/agp/kubin/venv/lib/python3.10/site-packages/anyio/to_thread.py",
line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File
"/home/agp/kubin/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py",
line 937, in run_sync_in_worker_thread
    return await future
  File
"/home/agp/kubin/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py",
line 867, in run
    result = context.run(func, *args)
  File
"/home/agp/kubin/extensions/kd-training/train_modules/train_tools.py", line
178, in prepare_dataset
    with open(caption_path) as f:
FileNotFoundError: [Errno 2] *No such file or directory:
'/home/agp/kubin/resized_data_set/gorgeous mustard schmear gradient sunset,
majestic horse, amazing texture, thick impasto.txt' -> png file is there
but it can't create caption file  *

**Comment by seruva19** [comment]
Oh, I see. You are having a caption in filename of png picture?

**Comment by adrianpuiu** [comment]
no, i assumed  it pickles the caption from the file name cause thats how i
do them usually /
so ill need to create a text caption file for each image in the dataset  ?

**Comment by seruva19** [comment]
Yes, I use the same scheme as in kohya_ss training scripts - there should be an image and text file with the same name as image, which contains caption. But I can add an option to capture text directly from filename, if you want, it's not difficult.

**Comment by adrianpuiu** [comment]
yes please would be faster for building the dataset.csv file this way

 os.path.splitext(path)   .. was it this one ?

**Comment by seruva19** [comment]
No problems, I will add in 10-20 minutes.

**Comment by adrianpuiu** [comment]
https://stackoverflow.com/questions/45113157/how-to-extract-the-file-name-from-a-file-path

check this one . thanks

**Comment by seruva19** [comment]
Added checkbox to extract captions from filename.

**Comment by adrianpuiu** [comment]
its perfect man, it worked flawlessly.
the training tabs are perfect to be honest and there is nothing else to
change about it .

**Comment by adrianpuiu** [comment]
attaching a prior training error. ... ill try to replicate tomorrow and get
a stacktrace .

**Comment by adrianpuiu** [comment]
ignore the last error . the issue was : full volume storage :)))

/dev/nvme0n1p6  275G  259G  2,2G 100% /home

**Pull request merged**
