### PR TITLE
updated the t2i layout 

### PR DESCRIPTION
**Pull request by adrianpuiu**
1. Updated the t2i.py layout to give it more of a workflow vibe to it.
2. Modified slider step values for guidance scales  from 1 to 0.5
3. Modified slider min values from 0 to 1

### CODE REVIEW

**Comment by seruva19** [comment]
That looks OK, will check and merge later, really busy rn on main job 😐

**Comment by adrianpuiu** [comment]
wait , i messed up with the latest push and rolled back the t2i file. can you upload it if you still have it on local ?

**Comment by adrianpuiu** [comment]
fixed and rolled back to latest changes and updated the i2i with similar layout

**Comment by seruva19** [comment]
Hey, I tried new UI and really appreciate your efforts, but I'll be honest - I prefer "my" old version of UI.
Obviously it's matter of taste. But I can't accept your PR.
I suggest two options:
- Either you will have your working fork with your own dedicated UI
- Or I can consider finding a way to customize app's UI so that it could eventually include your workflow view
 
That does not concern slider modifications, they are useful.

**Comment by adrianpuiu** [comment]
no worries man, it's ok, we all have a different way of doing things :) . but those 0 value on sliders do my head in :D

**Comment by seruva19** [comment]
OK, nice to hear that.
I will think about customizing structure UI, that would actually be interesting to implement as extension.
And, for sure, I will accept your sliders modifications)

**Comment by adrianpuiu** [comment]
could you also add an interrogator to the image gallery ? that would be nice to have

**Comment by seruva19** [comment]
Yeah, sure, I will.

**Pull request closed without merging**
