### PR TITLE
add support for diffusers + UI for settings management

### PR DESCRIPTION
**Pull request by seruva19**

### CODE REVIEW

**Comment by adrianpuiu** [comment]
waiting for the check pass :D

**Comment by seruva19** [comment]
I think I have to modify wiki as well, but I will do it later ;)
The development has slowed down for a bit because I (unfortunately) transitioned from full remote to hybrid work, and I don't have as much time as before to work on open-source projects.
And I am currently in the process of diving into another side project that is not connected with Kandinsky :)

**Comment by adrianpuiu** [comment]
things like this happen. i am supposed to actually work from Prague , but i work from Romania until they say to go and work from there.

**Comment by adrianpuiu** [comment]
File "/home/agp/kubin/src/models/model_diffusers.py", line 56, in prepare
    self.pipe_prior = KandinskyPriorPipeline.from_pretrained(
NameError: name 'KandinskyPriorPipeline' is not defined ... im selecting the diffusers pipeline and im getting this error message.

any idea why this would happen ? also saved the config settings

**Comment by seruva19** [comment]
Did you run "pip install -r diffusers/requirements.txt" before launching the app?

**Comment by adrianpuiu** [comment]
> Did you run "pip install -r diffusers/requirements.txt" before launching the app?

man no, but i did installed accelerate transformers and diffuses on my own and complete forgot  it needs 0.17  and above  to work... im running it now

**Comment by adrianpuiu** [comment]
already pulling the diffuser models

**Pull request merged**
