### PR TITLE
added start scripts

### PR DESCRIPTION
**Pull request by adrianpuiu**
created 2 small scripts to avoid to much typing

### CODE REVIEW

**Comment by seruva19** [comment]
That's handy, thank you! 
I want to make a small wrapper util to manage all updates/runs and do not force users to deal with CLI. Yet haven't got enough free time for it.

**Comment by adrianpuiu** [comment]
im also preparing the docker container file  , im just testing it now.

**Comment by adrianpuiu** [comment]
i can add a git pull into the start.* fies if you want

**Comment by seruva19** [comment]
Docker support will be huge. Although I have attempted to write a Dockerfile, I was unable to find an appropriate CUDA image and therefore decided not to spend any more time on it.
Regarding git pull, I believe it would be better to create a separate shell script for updates.

**Comment by adrianpuiu** [comment]
---> Running in a1f9c9315ca4
Removing intermediate container a1f9c9315ca4
 ---> 15da4cde8edf
Step 8/10 : COPY . .
its still building the container . will let you know if it works

**Comment by adrianpuiu** [comment]
it fails cause i forgot about the extension requirements :)) , ill modify it tomorrow

**Comment by seruva19** [comment]
OK. And btw you can force run without extensions with '--safe-mode' flag.

**Comment by adrianpuiu** [comment]
good o know, thanks

**Pull request merged**
